apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
  labels:
    app: fastapi-backend
spec:
  selector:
    app: fastapi-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
